config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => "home#index"

  get 'admin'   => 'admin/posts#index'

  namespace :admin do
    resources :users
    resources :posts

    get    'sign_in'   => 'sessions#new'
    post   'sign_in'   => 'sessions#create'
    delete 'sign_out'  => 'sessions#destroy'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  VALID_EMAIL_FORMAT= /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i

  validates :name, presence: true, length: {maximum: 50}
  validates :password, presence: true, length: {minimum: 6}, :on => :create
  validates :email, presence: true, length: {maximum: 260}, format: { with: VALID_EMAIL_FORMAT}, uniqueness: { case_sensitive: false }
  
  before_save { self.email = email.downcase }

  has_many :posts, dependent: :destroy
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  layout "admin"

  before_filter :valid_user
  
  def index
    @posts = current_user.posts.order("id DESC")
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    
    if @post.save
      ProcessMarkdownWorker.perform_async(@post.id)

      redirect_to [:admin, @post]
    else 
      render action: :new
    end
  end

  def update
    @post = Post.find(params[:id])

    @post.update_attributes(post_params)

    ProcessMarkdownWorker.perform_async(@post.id)

    redirect_to [:admin, @post]
  end

  def show
    @post ||= Post.find(params[:id])
  end

  def destroy
    Post.find(params[:id]).destroy

    redirect_to admin_posts_path
  end

  private
  def post_params
    params.require(:post).permit(:title, :markdown)
  end

  def valid_user
    redirect_to admin_sign_in_path unless logged_in?
  end
end

app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < ApplicationController
  layout "admin"
  
  def new
  end

  def create
    @user = User.find_by(email: params[:session][:email].downcase)
    
    if @user && @user.authenticate(params[:session][:password])
      sign_in

      redirect_to admin_path
    else
      render 'new'
    end
  end

  def sign_in
    session[:user_id] = @user.id
  end

  def destroy
    sign_out

    redirect_to admin_path
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  layout "admin"

  before_filter :valid_user, :except => [:new]
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      redirect_to [:admin, @user]
      
      sign_in
    else 
      render action: :new
    end
  end

  def index
    @users = User.all
  end

  def show
    @user ||= User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    user_params = params.require(:user).permit(:name, :email, :password, :password_confirmation)

    if user_params[:password].blank?
      user_params = user_params.except(:password, :password_confirmation) 
    end

    @user.update_attributes(user_params.except(:email))

    redirect_to [:admin, @user]
  end

  def destroy
    User.find(params[:id]).destroy

    redirect_to admin_users_path
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def valid_user
    redirect_to admin_sign_in_path unless logged_in?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include SessionsHelper
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.all.order("id DESC")
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
 
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in
    session[:user_id] = @user.id
  end

  def sign_out
    session.delete(:user_id)
    
    @current_user = nil
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def block_access
    if current_user.present?
       redirect_to admin_users_path
    end
  end

  def logged_in?
    !current_user.nil?
  end
end 

app/views/admin/posts/index.html.erb
<!-- Page Content -->
<div class="container">
  <div class="row">
    <!-- Post Content Column -->
    <div class="col-lg-12">
    	<h1 class="title">Posts <%= link_to "New Post", new_admin_post_path, class: "btn btn-outline-primary"%></h1>
    	<hr>

    	<ul class="list-group" id="posts">
    	  <% @posts.each do |post| %>
		    <li class="list-group-item">
		      <h4>
		      	  <%= post.title %>

			      <%= link_to "Excluir", [:admin, post], method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger btn-sm" %>
			      <%= link_to "Editar", [:admin, post], class: "btn btn-info btn-sm" %>
			  </h4>
		    </li>
		  <% end %>
		</ul>
	</div>
  </div>
</div>

app/views/admin/posts/new.html.erb
<!-- Page Content -->
<div class="container">
  <div class="row">
    <!-- Post Content Column -->
    <div class="col-lg-12">
      <h1 class="title">New Post</h1>
      <hr>

      <%= form_for [:admin, @post] do |f| %>
        <% if @post.errors.any? %>
          <div id="error_explanation">
            <div class="alert-error">
              O formulário contém <%= pluralize(@post.errors.count, "erro") %>.
            </div>
            
            <ul>
              <% @post.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title, class: "form-control"%>
        </div>
        
        <div class="form-group">
          <%= f.label :markdown %>
          <%= f.text_area :markdown, "data-provide": "markdown", id: "markdown-editor" %>
        </div>
        <prev class="prev"></prev>

        <div class="actions">
          <%= f.submit "Salvar", class: "btn btn-primary"%>

          <%= link_to "Voltar", admin_posts_path, class: "btn btn-warning" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/posts/show.html.erb
<!-- Page Content -->
<div class="container">
  <div class="row">
    <!-- Post Content Column -->
    <div class="col-lg-12">
      <h1 class="title"><%= @post.title %></h1>
      <hr>

      <%= form_for [:admin, @post] do |f| %>
        <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title, class: "form-control" %>
        </div>
        
        <div class="form-group">
          <%= f.label :markdown %>
          <%= f.text_area :markdown, "data-provide": "markdown", id: "markdown-editor" %>
        </div>
        <prev class="prev"></prev>

        <div class="actions">
          <%= f.submit "Salvar", class: "btn btn-primary"%>

          <%= link_to "Voltar", admin_posts_path, class: "btn btn-warning" %>

          <%= link_to "Excluir", [:admin, @post], method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %></td>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<!-- Page Content -->
<div class="container">
  <div class="row">
    <!-- Post Content Column -->
    <div class="col-lg-12">
    	<h1 class="title">Users</h1>
    	<hr>

    	<ul class="list-group" id="posts">
    	  <% @users.each do |user| %>
		    <li class="list-group-item">
		      <h4>
		      	  <%= user.name %>

			      <%= link_to "Excluir", [:admin, user], method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger btn-sm" %>
			      <%= link_to "Editar", [:admin, user], class: "btn btn-info btn-sm" %>
			  </h4>
		    </li>
		  <% end %>
		</ul>
	</div>
  </div>
</div>

app/views/admin/users/new.html.erb
<!-- Page Content -->
<div class="container">
  <div class="row">
    <!-- Post Content Column -->
    <div class="col-lg-3">
      <h1 class="title">New User </h1>
      <hr>

      <%= form_for [:admin, @user] do |f| %>
        <% if @user.errors.any? %>
          <div id="error_explanation">
            <div class="alert-error">
              O formulário contém <%= pluralize(@user.errors.count, "erro") %>.
            </div>
            
            <ul>
              <% @user.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: "form-control" %>
        </div>
        
        <div class="form-group">
          <%= f.label :email %>
          <%= f.email_field :email, class: "form-control" %>
        </div>
        
        <div class="form-group">
          <%= f.label :password %>
          <%= f.password_field :password, class: "form-control" %>
        </div>
        
        <div class="form-group">
          <%= f.label :password_confirmation %>
          <%= f.password_field :password_confirmation, class: "form-control" %>
        </div>

        <div class="actions">
          <%= f.submit "Salvar", class: "btn btn-primary" %>

          <%= link_to "Voltar", admin_users_path, class: "btn btn-warning" %>

          <%= link_to "Excluir", [:admin, @user], method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %></td>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/users/show.html.erb
<!-- Page Content -->
<div class="container">
  <div class="row">
    <!-- Post Content Column -->
    <div class="col-lg-12">
      <h1 class="title"><%= @user.name %> </h1>
      <hr>

      <%= form_for [:admin, @user] do |f| %>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: "form-control" %>
        </div>
        
        <div class="form-group">
          <%= f.label :email %>
          <%= f.email_field :email, class: "form-control", readonly: true %>
        </div>
        
        <div class="form-group">
          <%= f.label :password %>
          <%= f.password_field :password, class: "form-control" %>
        </div>
        
        <div class="form-group">
          <%= f.label :password_confirmation %>
          <%= f.password_field :password_confirmation, class: "form-control" %>
        </div>

        <div class="actions">
          <%= f.submit "Salvar", class: "btn btn-primary" %>

          <%= link_to "Voltar", admin_users_path, class: "btn btn-warning" %>

          <%= link_to "Excluir", [:admin, @user], method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %></td>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<!-- Page Content -->
<div class="container">
  <div class="row">
    <!-- Post Content Column -->
    <div class="col-lg-8">
      <% @posts.each do |post| %>
        <!-- Title -->
        <h1 class="mt-4"><%= post.title %></h1>

        <!-- Author -->
        <p class="lead">
          by
          <%= post.user.name %>
        </p>
        <hr>

        <!-- Date/Time -->
        <p><%= post.created_at %></p>
        <hr>

        <!-- Post Content -->
        <%= raw post.html %>
      <% end %>
    </div>
  </div>
  <!-- /.row -->
</div>
<!-- /.container -->

app/views/layouts/_header.html.erb
<header>
  <%= render "shared/header-user" if logged_in? %>

  <nav class="navbar navbar-default navbar-static-top"">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

        <%= link_to "Blog", root_path, class: "navbar-brand" %>
      </div>

      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-right">
          <li class="<%= "active" if controller_name.eql?('admin') %>"><%= link_to "Login", admin_sign_in_path %></li>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <title>Admin</title>
  </head>

  <body>
  	<%= render 'layouts/header' %>

    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_footer.html.erb
<!-- Footer -->
<footer class="py-5 bg-dark">
  <div class="container">
    <p class="m-0 text-center text-white">Copyright &copy; Blog 2017</p>
  </div>
  <!-- /.container -->
</footer>

app/views/shared/_header-user.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top"">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Blog", root_path, class: "navbar-brand" %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li class="<%= "active" if controller_name.eql?('posts') %>"><%= link_to "Posts", admin_posts_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Users <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Users", admin_users_path %></li>
            <li><%= link_to "Profile", [:admin, current_user] %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Log out", admin_sign_out_path, method: "delete" %></li>
          </ul>
        </li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>